//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace retail
{
    using System;
    using System.Collections.Generic;
    
    public partial class cart
    {
        public int cartID { get; set; }
        public int userID { get; set; }
        public int productID { get; set; }
    
        public virtual product product { get; set; }
        public virtual users users { get; set; }
    }
}
