//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace retail
{
    using System;
    using System.Collections.Generic;
    
    public partial class material
    {
        public material()
        {
            this.product = new HashSet<product>();
        }
    
        public int materialID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<product> product { get; set; }
    }
}
