//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace retail
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class saleEntities : DbContext
    {
        public saleEntities()
            : base("name=saleEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<brand> brand { get; set; }
        public DbSet<category> category { get; set; }
        public DbSet<colour> colour { get; set; }
        public DbSet<country> country { get; set; }
        public DbSet<department> department { get; set; }
        public DbSet<fastener> fastener { get; set; }
        public DbSet<material> material { get; set; }
        public DbSet<payment> payment { get; set; }
        public DbSet<product> product { get; set; }
        public DbSet<role> role { get; set; }
        public DbSet<sales> sales { get; set; }
        public DbSet<size> size { get; set; }
        public DbSet<status> status { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<users> users { get; set; }
        public DbSet<warehouse> warehouse { get; set; }
        public DbSet<wear> wear { get; set; }
        public DbSet<zakaz> zakaz { get; set; }
    }
}
