//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace retail
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public product()
        {
            this.cart = new HashSet<cart>();
            this.sales = new HashSet<sales>();
            this.warehouse = new HashSet<warehouse>();
            this.zakaz = new HashSet<zakaz>();
        }
    
        public int productID { get; set; }
        public int wearID { get; set; }
        public int departID { get; set; }
        public int categoryID { get; set; }
        public int brandID { get; set; }
        public int countryID { get; set; }
        public int materialID { get; set; }
        public Nullable<int> fastenerID { get; set; }
        public Nullable<int> colourID { get; set; }
        public Nullable<int> sizeID { get; set; }
        public string image { get; set; }
        public int price { get; set; }
    
        public virtual brand brand { get; set; }
        public virtual ICollection<cart> cart { get; set; }
        public virtual category category { get; set; }
        public virtual colour colour { get; set; }
        public virtual country country { get; set; }
        public virtual department department { get; set; }
        public virtual fastener fastener { get; set; }
        public virtual material material { get; set; }
        public virtual size size { get; set; }
        public virtual wear wear { get; set; }
        public virtual ICollection<sales> sales { get; set; }
        public virtual ICollection<warehouse> warehouse { get; set; }
        public virtual ICollection<zakaz> zakaz { get; set; }
    }
}
