//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace retail
{
    using System;
    using System.Collections.Generic;
    
    public partial class role
    {
        public role()
        {
            this.users = new HashSet<users>();
        }
    
        public int roleID { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<users> users { get; set; }
    }
}
