//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace retail
{
    using System;
    using System.Collections.Generic;
    
    public partial class sales
    {
        public int salesID { get; set; }
        public int productID { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual product product { get; set; }
    }
}
