//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace retail
{
    using System;
    using System.Collections.Generic;
    
    public partial class users
    {
        public users()
        {
            this.zakaz = new HashSet<zakaz>();
        }
    
        public int userID { get; set; }
        public string surname { get; set; }
        public string name { get; set; }
        public string patronymic { get; set; }
        public System.DateTime birthdate { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public int roleID { get; set; }
    
        public virtual role role { get; set; }
        public virtual ICollection<zakaz> zakaz { get; set; }
    }
}
