//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace retail
{
    using System;
    using System.Collections.Generic;
    
    public partial class zakaz
    {
        public int zakazID { get; set; }
        public string name { get; set; }
        public int productID { get; set; }
        public int statusID { get; set; }
        public int paymentID { get; set; }
        public int userID { get; set; }
        public Nullable<System.DateTime> orderDate { get; set; }
    
        public virtual payment payment { get; set; }
        public virtual product product { get; set; }
        public virtual status status { get; set; }
        public virtual users users { get; set; }
    }
}
